# Generated by Django 6.0.3 on 2026-04-09 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approval_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='external_approver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
