# Generated by Django 6.0.3 on 2026-04-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_approval_pending_document_external_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
