# Generated by Django 6.0.3 on 2026-04-16 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('office_order', 'Office Order'), ('notification', 'Notification'), ('circular', 'Circular'), ('note', 'Note'), ('correspondence', 'Correspondence to Outside Party'), ('other', 'Others')], default='office_order', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sender_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_docs', to='core.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='sender_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
