# Generated by Django 6.0.3 on 2026-04-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_date_received_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
    ]
