# Generated by Django 6.0.3 on 2026-04-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_document_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ref_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
