# Generated by Django 6.0.3 on 2026-04-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_ref_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='ref_no',
            new_name='ref_number',
        ),
    ]
