# Generated by Django 6.0.3 on 2026-04-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_ref_no_document_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
